"use strict";

const DATA_URL = "data/synchronized_walk.csv";
const DEFAULT_CHANNEL_SUFFIXES = ["master_right_walk_acc_y", "slave_left_walk_acc_y"];
const COLORS = [
  "#5eead4",
  "#60a5fa",
  "#fbbf24",
  "#f472b6",
  "#a78bfa",
  "#fb7185",
  "#34d399",
  "#f97316",
];

const elements = {
  status: document.querySelector("#status"),
  rangeStart: document.querySelector("#range-start"),
  rangeEnd: document.querySelector("#range-end"),
  applyRange: document.querySelector("#apply-range"),
  resetRange: document.querySelector("#reset-range"),
  channelSearch: document.querySelector("#channel-search"),
  channelList: document.querySelector("#channel-list"),
  selectedCount: document.querySelector("#selected-count"),
  selectAll: document.querySelector("#select-all"),
  clearAll: document.querySelector("#clear-all"),
  emptyState: document.querySelector("#empty-state"),
  plot: document.querySelector("#plot"),
};

const state = {
  rows: [],
  channels: [],
  selectedChannels: new Set(),
  fullRange: [0, 0],
};

function parseCsv(text) {
  const lines = text.trimEnd().split(/\r?\n/);
  if (lines.length < 2) {
    throw new Error("The synchronized CSV contains no data rows.");
  }

  // This viewer consumes the numeric CSV generated by sync_walk_csv.py. Its
  // fields contain no commas or quoted text, so direct splitting avoids shipping
  // a second parsing dependency with the public page.
  const headers = lines[0].split(",");
  const rows = lines.slice(1).map((line) => {
    const values = line.split(",");
    return Object.fromEntries(
      headers.map((header, index) => {
        const rawValue = values[index] ?? "";
        return [header, rawValue === "" ? null : Number(rawValue)];
      }),
    );
  });

  if (headers[0] !== "fid" || rows.some((row) => !Number.isFinite(row.fid))) {
    throw new Error("The synchronized CSV has an invalid fid column.");
  }
  return { headers, rows };
}

function channelLabel(channel) {
  return channel
    .replace("master_right_", "Right · ")
    .replace("slave_left_", "Left · ")
    .replaceAll("_", " ");
}

function filteredChannels() {
  const query = elements.channelSearch.value.trim().toLowerCase();
  return state.channels.filter(
    (channel) =>
      channel.toLowerCase().includes(query) ||
      channelLabel(channel).toLowerCase().includes(query),
  );
}

function updateSelectedCount() {
  elements.selectedCount.textContent = `${state.selectedChannels.size} selected`;
}

function renderChannelList() {
  elements.channelList.replaceChildren();
  for (const channel of filteredChannels()) {
    const label = document.createElement("label");
    label.className = "channel-option";

    const checkbox = document.createElement("input");
    checkbox.type = "checkbox";
    checkbox.checked = state.selectedChannels.has(channel);
    checkbox.addEventListener("change", () => {
      if (checkbox.checked) {
        state.selectedChannels.add(channel);
      } else {
        state.selectedChannels.delete(channel);
      }
      updateSelectedCount();
      renderPlot();
    });

    const text = document.createElement("span");
    text.textContent = channelLabel(channel);
    label.append(checkbox, text);
    elements.channelList.append(label);
  }
  updateSelectedCount();
}

function selectedRange() {
  const requestedStart = Number(elements.rangeStart.value);
  const requestedEnd = Number(elements.rangeEnd.value);
  const [fullStart, fullEnd] = state.fullRange;
  if (!Number.isFinite(requestedStart) || !Number.isFinite(requestedEnd)) {
    throw new Error("Both FID range values must be numbers.");
  }
  if (requestedStart >= requestedEnd) {
    throw new Error("The start FID must be smaller than the end FID.");
  }
  return [
    Math.max(fullStart, Math.round(requestedStart)),
    Math.min(fullEnd, Math.round(requestedEnd)),
  ];
}

function showRangeError(message) {
  elements.status.textContent = message;
  elements.status.classList.add("error");
}

function renderPlot() {
  const selected = state.channels.filter((channel) =>
    state.selectedChannels.has(channel),
  );
  elements.emptyState.hidden = selected.length > 0;
  elements.plot.hidden = selected.length === 0;
  if (selected.length === 0) {
    Plotly.purge(elements.plot);
    return;
  }

  let range;
  try {
    range = selectedRange();
  } catch (error) {
    showRangeError(error.message);
    return;
  }

  elements.status.classList.remove("error");
  elements.status.textContent = `${state.rows.length.toLocaleString()} samples · ${selected.length} subplot${selected.length === 1 ? "" : "s"}`;
  const visibleRows = state.rows.filter(
    (row) => row.fid >= range[0] && row.fid <= range[1],
  );

  // Give every trace its own y-axis domain while matching all x-axes to the
  // first one. The final subplot alone renders x tick labels, producing stacked
  // independent scales with synchronized zoom, pan, and hover positioning.
  const layout = {
    paper_bgcolor: "#111827",
    plot_bgcolor: "#111827",
    font: { color: "#c9d5e5", size: 11 },
    height: Math.max(560, selected.length * 190),
    margin: { l: 130, r: 30, t: 28, b: 55 },
    hovermode: "x unified",
    showlegend: false,
    uirevision: `${range[0]}:${range[1]}:${selected.join("|")}`,
  };
  const traces = selected.map((channel, index) => {
    const axisNumber = index + 1;
    const axisSuffix = axisNumber === 1 ? "" : String(axisNumber);
    const cellHeight = 1 / selected.length;
    const domainTop = 1 - index * cellHeight;
    const domainBottom = 1 - (index + 1) * cellHeight + 0.035;
    const xAxisName = `xaxis${axisSuffix}`;
    const yAxisName = `yaxis${axisSuffix}`;

    layout[xAxisName] = {
      anchor: `y${axisSuffix}`,
      matches: axisNumber === 1 ? undefined : "x",
      range,
      showticklabels: index === selected.length - 1,
      title: index === selected.length - 1 ? { text: "FID" } : undefined,
      gridcolor: "#263348",
      zerolinecolor: "#3b4d68",
    };
    layout[yAxisName] = {
      anchor: `x${axisSuffix}`,
      domain: [Math.max(0, domainBottom), domainTop],
      title: { text: channelLabel(channel), standoff: 12 },
      gridcolor: "#263348",
      zerolinecolor: "#3b4d68",
      automargin: true,
    };

    return {
      type: "scattergl",
      mode: "lines",
      name: channelLabel(channel),
      x: visibleRows.map((row) => row.fid),
      y: visibleRows.map((row) => row[channel]),
      xaxis: `x${axisSuffix}`,
      yaxis: `y${axisSuffix}`,
      connectgaps: false,
      line: { color: COLORS[index % COLORS.length], width: 1.35 },
      hovertemplate: "%{y:.4f}<extra></extra>",
    };
  });

  Plotly.react(elements.plot, traces, layout, {
    responsive: true,
    displaylogo: false,
    scrollZoom: true,
    modeBarButtonsToRemove: ["lasso2d", "select2d"],
  });

  elements.plot.removeAllListeners?.("plotly_relayout");
  elements.plot.on("plotly_relayout", (event) => {
    const start = event["xaxis.range[0]"];
    const end = event["xaxis.range[1]"];
    if (Number.isFinite(start) && Number.isFinite(end)) {
      elements.rangeStart.value = Math.round(start);
      elements.rangeEnd.value = Math.round(end);
    }
  });
}

function enableControls() {
  for (const control of [
    elements.rangeStart,
    elements.rangeEnd,
    elements.applyRange,
    elements.resetRange,
    elements.channelSearch,
    elements.selectAll,
    elements.clearAll,
  ]) {
    control.disabled = false;
  }
}

async function loadData() {
  try {
    const response = await fetch(DATA_URL);
    if (!response.ok) {
      throw new Error(`Data request failed with HTTP ${response.status}.`);
    }
    const { headers, rows } = parseCsv(await response.text());
    state.rows = rows;
    state.channels = headers.slice(1);
    state.fullRange = [rows[0].fid, rows.at(-1).fid];
    state.selectedChannels = new Set(
      DEFAULT_CHANNEL_SUFFIXES.filter((channel) => state.channels.includes(channel)),
    );

    elements.rangeStart.min = state.fullRange[0];
    elements.rangeStart.max = state.fullRange[1];
    elements.rangeStart.value = state.fullRange[0];
    elements.rangeEnd.min = state.fullRange[0];
    elements.rangeEnd.max = state.fullRange[1];
    elements.rangeEnd.value = state.fullRange[1];
    enableControls();
    renderChannelList();
    renderPlot();
  } catch (error) {
    elements.status.textContent = `Unable to load viewer: ${error.message}`;
    elements.status.classList.add("error");
  }
}

elements.applyRange.addEventListener("click", renderPlot);
elements.resetRange.addEventListener("click", () => {
  [elements.rangeStart.value, elements.rangeEnd.value] = state.fullRange;
  renderPlot();
});
elements.channelSearch.addEventListener("input", renderChannelList);
elements.selectAll.addEventListener("click", () => {
  for (const channel of filteredChannels()) {
    state.selectedChannels.add(channel);
  }
  renderChannelList();
  renderPlot();
});
elements.clearAll.addEventListener("click", () => {
  state.selectedChannels.clear();
  renderChannelList();
  renderPlot();
});

loadData();
